/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package config;


import arbol.Arbol;
import java.io.File;
import java.io.IOException;
import java.net.InetAddress;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Base64;
import java.util.Date;
import java.util.List;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.h2.tools.Backup;
import org.h2.tools.DeleteDbFiles;
import org.h2.tools.Restore;

/**
 *
 * @author Jaiver
 */
public class Config extends javax.swing.JInternalFrame {

    /**
     * Creates new form Home
     */
    Icon check;
    String fecha;

    public Config() {
        initComponents();
              
        
        jButton3.setEnabled(arbol.Arbol.val);        
        jButton6.setEnabled(arbol.Arbol.val);        
         jButton8.setEnabled(arbol.Arbol.val);
         
       
        fecha = "Backup " + new SimpleDateFormat("dd-MMMM-yyyy").format(new Date());

        //olvidar();
        check = new ImageIcon(Config.class.getResource("/icon/Check.png"));
          try {
            String Rport = String.valueOf(Integer.parseInt(new String(Arbol.Leer("port.bin"), "UTF-8")));
            jLabel1.setText(InetAddress.getLocalHost().getHostAddress() + ":" + Rport);
        } catch (Exception e) {
            jLabel1.setText("No Conectado");
        }
    }

    public void olvidar() {
        jButton9.setVisible(false);
        jLabel1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Configuracion");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Opciones", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 3, 24), new java.awt.Color(204, 0, 51))); // NOI18N

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton8.setForeground(new java.awt.Color(0, 51, 153));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Base_Imp.png"))); // NOI18N
        jButton8.setText("Importar Datos");
        jButton8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(0, 51, 153));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Base_Exp.png"))); // NOI18N
        jButton6.setText("Exportar Datos");
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 102, 51));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Xls.png"))); // NOI18N
        jButton3.setText("Exportar Excel");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton9.setForeground(new java.awt.Color(0, 51, 153));
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Confi.png"))); // NOI18N
        jButton9.setText("Modificar Puerto");
        jButton9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton10.setForeground(new java.awt.Color(0, 102, 51));
        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Refresh.png"))); // NOI18N
        jButton10.setText("Actualizar");
        jButton10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                            .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(jButton8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Dialog", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sin Conexión");
        jLabel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Direccion Servidor", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 3, 24), new java.awt.Color(204, 0, 51))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int desi = JOptionPane.showConfirmDialog(this, "¿ Desea Exportar la Base de Datos a Excel?", "Confirmar", 2);

        if (desi == 0) {
            JFileChooser chooser = new JFileChooser();
            FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivos de Excel", "xls");
            chooser.setFileFilter(filter);
            chooser.setDialogTitle("Guardar Archivo");
            chooser.setAcceptAllFileFilterUsed(false);
            if (chooser.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
                List<JTable> tb = new ArrayList<>();
                List<String> nom = new ArrayList<>();

               
                tb.add(new personas.ConsultaPersonas().getTabla());
                nom.add("Personas");

                String file = chooser.getSelectedFile().toString().concat(".xls");
                try {
                    Exporter e = new Exporter(new File(file), tb, nom);
                    if (e.export()) {
                        JOptionPane.showMessageDialog(this, "Los Datos Fueron Exportados", "Exito", -1, check);
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, e.getMessage(), " Error", 0);
                }
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    public void exportar() {
        try {

            JFileChooser chooser = new JFileChooser();
            FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivo Zip", "zip");
            chooser.setFileFilter(filter);
            chooser.setDialogTitle("Guardar Archivo de Restauracion");

            chooser.setSelectedFile(new File(fecha));
            chooser.setAcceptAllFileFilterUsed(false);
            if (chooser.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
                Backup.execute(chooser.getSelectedFile().getAbsolutePath() + ".zip", "~/", "tree", false);
                JOptionPane.showMessageDialog(this, "Los Datos Fueron Exportados", "Exito", -1, check);
            }
        } catch (Exception error) {
            JOptionPane.showMessageDialog(this, error.getMessage(), "Error", 0);
        }

    }

    public void importar() {

        try {
            JFileChooser chooser = new JFileChooser();
            FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivo Zip", "zip");
            chooser.setFileFilter(filter);
            chooser.setSelectedFile(new File(fecha));
            chooser.setDialogTitle("Abrir Archivo de Restauracion");
            chooser.setAcceptAllFileFilterUsed(false);
            
            if (chooser.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
                DeleteDbFiles.execute("~/", "tree", false);
                Restore.execute(chooser.getSelectedFile().getAbsolutePath(), "~/", "tree");
                JOptionPane.showMessageDialog(this, "Los Datos Fueron Restaurados", "Exito", -1, check);
            }
        } catch (Exception error) {
            JOptionPane.showMessageDialog(this, error.getMessage(), "Error", 0);
        }

    }




    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
   
        int desi;

        desi = JOptionPane.showConfirmDialog(this, "¿ Desea Exportar la Base de Datos?", "Confirmar", 2);

        if (desi == 0) {
            exportar();
        }

    }//GEN-LAST:event_jButton6ActionPerformed


    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        int desi;

        desi = JOptionPane.showConfirmDialog(this, "¿ Desea Importar Datos al Programa?", "Confirmar", 2, 0);

        if (desi == 0) {

            desi = JOptionPane.showConfirmDialog(this, "¿ Esta Seguro?", "Confirmar", 2, 0);

            if (desi == 0) {

                desi = JOptionPane.showConfirmDialog(this, "Ultima Oportunidad \n¿Desea Importar los Datos?", "Confirmar", 2, 0);

                if (desi == 0) {
                    importar();
                }
            }
        }
    }//GEN-LAST:event_jButton8ActionPerformed

  
    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        try {

            if (!Paths.get("port.bin").toFile().exists()) {
                Arbol.Escribir("1234".getBytes(), "port.bin");
            }

            String Rport = String.valueOf(Integer.parseInt(new String(Arbol.Leer("port.bin"), "UTF-8")));

            String Wport = String.valueOf(Integer.parseInt(JOptionPane.showInputDialog(this, "Escriba el numero del Puerto ", Rport)));

            Arbol.Escribir(Wport.getBytes(), "port.bin");
            JOptionPane.showMessageDialog(this, "El Puerto ha Sido Modifiado.\n Reinicie la Aplicacion para hacer los cambios", "Exito", -1, check);
        } catch (Exception error) {
            JOptionPane.showMessageDialog(this, error.getMessage(), "Error", 0);
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
try {

            if (!Paths.get("company.bin").toFile().exists()) {
                Arbol.Escribir(Base64.getEncoder().encode("Software Stock 3.0".getBytes()), "company.bin");
            }

            String Rport = new String(Base64.getDecoder().decode(Arbol.Leer("company.bin")), "UTF-8");

            String Wport = JOptionPane.showInputDialog(this, "Escriba el nombre del Negocio ", Rport);

            Arbol.Escribir(Base64.getEncoder().encode(Wport.getBytes()), "company.bin");
            JOptionPane.showMessageDialog(this, "La Aplicacion ha sido Actualizada.\n Reinicie la Aplicacion para hacer los cambios", "Exito", -1, check);
        } catch (Exception error) {
            JOptionPane.showMessageDialog(this, error.getMessage(), "Error", 0);
        }    }//GEN-LAST:event_jButton10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Config.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Config.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Config.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Config.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Config().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
